import streamlit as st
import pandas as pd
import plotly.express as px
import os

# Set page config
st.set_page_config(page_title="Customer Segmentation & Market Basket Analysis", layout="wide")

st.title("📊 Customer Segmentation & Market Basket Analysis Dashboard")

# Define data paths
DATA_DIR = "data/processed"
CLUSTERS_FILE = os.path.join(DATA_DIR, "customer_clusters_from_rules.csv")
RULES_FILE = os.path.join(DATA_DIR, "rules_apriori_filtered.csv")

@st.cache_data
def load_data():
    try:
        clusters_df = pd.read_csv(CLUSTERS_FILE)
        rules_df = pd.read_csv(RULES_FILE)
        return clusters_df, rules_df
    except FileNotFoundError as e:
        st.error(f"Error loading data: {e}")
        return None, None

clusters_df, rules_df = load_data()

if clusters_df is not None and rules_df is not None:
    
    # --- Tab 1: Customer Segmentation ---
    st.header("1. Customer Segmentation (RFM)")
    
    st.markdown("""
    **RFM Analysis** groups customers based on:
    - **Recency**: How recently did the customer purchase?
    - **Frequency**: How often do they purchase?
    - **Monetary**: How much do they spend?
    """)

    col1, col2 = st.columns([1, 2])

    with col1:
        st.subheader("Cluster Summary")
        if 'cluster' in clusters_df.columns:
            cluster_summary = clusters_df.groupby('cluster')[['Recency', 'Frequency', 'Monetary']].mean().reset_index()
            st.dataframe(cluster_summary.style.format("{:.2f}"))
            
            st.info(f"Total Customers: {len(clusters_df)}")
        else:
            st.warning("Cluster column not found in data.")

    with col2:
        st.subheader("3D Visualization")
        if 'cluster' in clusters_df.columns:
            fig = px.scatter_3d(
                clusters_df, 
                x='Recency', 
                y='Frequency', 
                z='Monetary',
                color='cluster',
                opacity=0.7,
                title="3D View of Customer Clusters"
            )
            st.plotly_chart(fig, use_container_width=True)

    # --- Tab 2: Association Rules ---
    st.markdown("---")
    st.header("2. Market Basket Analysis (Association Rules)")
    
    st.markdown("Explore the rules generated by the Apriori algorithm.")

    # Filters
    col_filter1, col_filter2, col_filter3 = st.columns(3)
    
    with col_filter1:
        min_support = st.slider("Min Support", 
                                float(rules_df['support'].min()), 
                                float(rules_df['support'].max()), 
                                float(rules_df['support'].min()))
    
    with col_filter2:
        min_confidence = st.slider("Min Confidence", 
                                   float(rules_df['confidence'].min()), 
                                   float(rules_df['confidence'].max()), 
                                   float(rules_df['confidence'].min()))
        
    with col_filter3:
        min_lift = st.slider("Min Lift", 
                             float(rules_df['lift'].min()), 
                             float(rules_df['lift'].max()), 
                             float(rules_df['lift'].min()))

    # Apply filters
    filtered_rules = rules_df[
        (rules_df['support'] >= min_support) &
        (rules_df['confidence'] >= min_confidence) &
        (rules_df['lift'] >= min_lift)
    ]

    st.write(f"Showing {len(filtered_rules)} rules out of {len(rules_df)}")

    # Display Rules Table
    st.dataframe(
        filtered_rules[['rule_str', 'support', 'confidence', 'lift', 'zhangs_metric']].sort_values(by='lift', ascending=False),
        use_container_width=True
    )

    # Scatter Plot for Rules
    if not filtered_rules.empty:
        st.subheader("Rules Scatter Plot")
        fig_rules = px.scatter(
            filtered_rules,
            x="support",
            y="confidence",
            size="lift",
            color="lift",
            hover_data=["rule_str"],
            title="Support vs Confidence (Size = Lift)"
        )
        st.plotly_chart(fig_rules, use_container_width=True)

else:
    st.warning("Please ensure data files are present in 'data/processed/'")
